# Pixel Theme Configuration

logo: /images/pixel-logo.webp
email:
  126: he_zexu@126.com
  qq: 529904017@qq.com
vx:
  id: HTGoodBoy
  image: /images/vx.jpg
tiktok:
  id: 1570554360
  image: /images/tiktok.png
author: 粥记捣蛋

# Writing Settings
## 自动摘要设置
excerpt_depth: 5  # 自动摘要的标题层级
auto_excerpt:
  enable: true    # 启用自动摘要
  length: 150     # 自动摘要的长度（字符数）

# Article Display
article:
  show_excerpt: true  # 在首页显示文章摘要
  show_date: true     # 显示文章日期
  show_categories: true  # 显示文章分类
  show_tags: true      # 显示文章标签
  show_copyright: true  # 显示文章版权声明

# Navigation
nav:
  - text: 首页  # 数组的第一个元素
    path: /index  # 数组的第二个元素
  - text: 碧海苍云录
    path: /bhcyl
  - text: 归档  # 数组的第一个元素
    path: /archives  # 数组的第二个元素
  - text: 关于我  # 数组的第一个元素
    path: /about  # 数组的第二个元素

# Comments
comments:
  disqus_shortname:  # Disqus 评论系统短名称
  enable: false      # 是否启用评论功能